RS-0: Loading was added when creating/updating referral and when downloading the CV
Apex-CS/referral-system-ui pull request #14
Opened 2023-10-02 22:52 UTC by BC-SRodriguez

- Loading was added when creating/updating referral and when downloading the CV.
- Fixed error when updating referrals.

2023-10-06 18:05 UTC, clopezh commented on src/components/referral/ReferralForm.tsx
> +                    setIsLoading(false);
I can see that you disabled the loading if an error happened, but what if the event was success? I know you're pushing to another route, but I think you need to setLoading as true before you call snackbar.success in all actions where you're using setIsLoading

2023-10-06 18:09 UTC, clopezh requested changes
Hi @BC-SRodriguez, Thank you for all the changes you did, I only have 2 questions & feedback could you please take a look? and if you have any question please let me know.

2023-10-06 18:09 UTC, clopezh commented on src/components/referral/ReferralForm.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
Instead of creating new states, you can use the isLoading prop from the customHook that call the API: 
useCreateReferrals() has a property called isLoadingCreateReferral that you can use to show a single loading icon or disabled.

Same apply for the isDownloadingCV.

2023-10-09 19:01 UTC, BC-SRodriguez commented
HI @clopezh,

I addressed your comments, could you review it again please? ♻️

2023-10-10 18:01 UTC, clopezh approved these changes

2023-10-10 18:01 UTC, merged